### ISSUE TITLE
Plugin hijacks the "Activate the selected layer" icon

### ISSUE THREAD

**Issue by don-vip** [JOSM/geojson#8]
In layers dialog the third button icon is replaced by the plugin icon when installed, probably because of a name clash.

**Comment by floscher** [comment]
@don-vip I'm currently a bit confused about the ant build of this plugin.

The sources are located in [`src/main/java`](https://github.com/JOSM/geojson/tree/36aeb8b43c332e335abd281c7061bc8f6f103580/src/main/java), the images in [`images`](https://github.com/JOSM/geojson/tree/36aeb8b43c332e335abd281c7061bc8f6f103580/images) as well as in [`src/main/resources/images`](https://github.com/JOSM/geojson/tree/36aeb8b43c332e335abd281c7061bc8f6f103580/src/main/resources/images). The [`build.xml` file](https://github.com/JOSM/geojson/blob/36aeb8b43c332e335abd281c7061bc8f6f103580/build.xml) does not modify anything to adjust for the different source directory.
The Ant property `plugin.src.dir` is immutable, so could not be adjusted to something different. It's anyway not used to determine, which directory to compile. So the `compile` task compiles the directory `src`, right?

On Jenkins the Ant build seems to work and produces the *.jar file correctly (I would expect package errors, because of the extra directories `main/java`‽).

Is there some Ant magic at work that fixes the source directory automatically? Should something be done about this?

Would it be ok, if I added the following to `build.xml` and moved `images` and `data` into `src/main/resources` in order to get rid of the duplicate `images` directories?:
```xml
<target name="setup-dist-default">
  <copy todir="${plugin.build.dir}/resources" failonerror="no" includeemptydirs="no">
    <fileset dir="src/main/resources/resources"/>
  </copy>
  <copy todir="${plugin.build.dir}/images" failonerror="no" includeemptydirs="no">
    <fileset dir="src/main/resources/images"/>
  </copy>
  <copy todir="${plugin.build.dir}/data" failonerror="no" includeemptydirs="no">
    <fileset dir="src/main/resources/data"/>
  </copy>
  <copy todir="${plugin.build.dir}">
    <fileset dir=".">
      <include name="README*"/>
      <include name="LICENSE*"/>
    </fileset>
  </copy>
</target>
```

**Comment by don-vip** [comment]
There is no Ant magic afaik. I don't understand neither how it works. Feel free to adapt it :) You can run ant -v to get debug output.

**Comment by floscher** [comment]
Not even dark magic that nobody understands and always emerges unexpectedly? :wink: :wink: At least it's in our favour, but I'll see what I can do to make it more straightforward…

I currently don't have a working environment for JOSM builds with Ant set up. So I'll try to adjust it and hope that Jenkins won't complain and I don't break anything else :crossed_fingers: .
